Listen 443

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# Redirección HTTP (80) a HTTPS (443)
<VirtualHost *:80>
    ServerName blog.local
    Redirect permanent / https://blog.local/
</VirtualHost>

# VirtualHost seguro (HTTPS / 443)
<VirtualHost *:443>
    ServerName blog.local
    DocumentRoot /usr/local/apache2/htdocs/blog.local

    SSLEngine on
    SSLCertificateFile /usr/local/apache2/conf/ssl/blog.local.pem
    SSLCertificateKeyFile /usr/local/apache2/conf/ssl/blog.local-key.pem

    <Directory /usr/local/apache2/htdocs/blog.local>
        AllowOverride All
        Require all granted
    </Directory>

    # Configuración de Reverse Proxy con remoción de prefijo /api
    ProxyPreserveHost On
    ProxyPass /api/ http://host.docker.internal:9000/
    ProxyPassReverse /api/ http://host.docker.internal:9000/

    ErrorLog /usr/local/apache2/logs/blog.local-ssl-error.log
    CustomLog /usr/local/apache2/logs/blog.local-ssl-access.log combined
</VirtualHost>